# Netlify Configuration for Studio Arteamo Portfolio - Performance Optimized

[build]
  # Directory to publish (already built, no build command needed)
  publish = "."
  
# Build plugins for optimization
[[plugins]]
  # Automatic image optimization to WebP/AVIF
  package = "netlify-plugin-image-optim"

[[plugins]]
  # HTML minification
  package = "netlify-plugin-minify-html"
  [plugins.inputs]
    contexts = ["production"]

[[plugins]]
  # Performance monitoring
  package = "@netlify/plugin-lighthouse"
  [plugins.inputs]
    fail_deploy_on_score_thresholds = false
    thresholds.performance = 0.9

# Redirects for clean URLs and performance
[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

# Redirect to optimized site
[[redirects]]
  from = "/index.html"
  to = "/website1-minimalist/"
  status = 301
  force = true

# Headers for maximum performance
[[headers]]
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    
    # Performance headers
    Cache-Control = "public, max-age=0, must-revalidate"
    
    # Enable connection keep-alive
    Connection = "keep-alive"

# Aggressive caching for static assets
[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Image caching
[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.jpeg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.webp"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.avif"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Preload critical resources
[[headers]]
  for = "/website1-minimalist/"
  [headers.values]
    Link = '''
    </website1-minimalist/critical.min.css>; rel=preload; as=style,
    </website1-minimalist/styles.min.css>; rel=preload; as=style,
    </translations.min.js>; rel=preload; as=script,
    <https://fonts.googleapis.com>; rel=preconnect,
    <https://fonts.gstatic.com>; rel=preconnect; crossorigin
    '''

# Asset optimization rules
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  minify = true

[build.processing.images]
  compress = true

# Performance-focused environment variables
[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--no-audit --no-fund"

# Faster builds
[build.cache]
  paths = [
    "node_modules/",
    ".cache/"
  ]