/**
 * Project Configuration
 *
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 *
 * This file is automatically generated from markdown files in content/projects/
 * by the sync-markdown-to-config.js script.
 *
 * To modify projects:
 * 1. Edit markdown files in content/projects/
 * 2. Run: node sync-markdown-to-config.js
 * 3. Or use the CMS at /admin-cms/ (commits trigger auto-sync)
 *
 * Last updated: 2025-12-14T23:08:34.776Z
 * Projects count: 11
 */

const projectConfig = {
  "Apartament Flavia Garden 2024": {
    "name": {
      "bg": "Апартамент Флавия Гардън",
      "en": "Flavia Garden Apartment",
      "ru": "Апартамент Флавия Гарден",
      "es": "Apartamento Flavia Garden",
      "he": "",
      "zh": ""
    },
    "subtitle": {
      "bg": "Модерен Дом",
      "en": "Modern Living",
      "ru": "Современная Жизнь",
      "es": "Vida Moderna",
      "he": "",
      "zh": ""
    },
    "description": {
      "bg": "Модерно убежище, съчетаващо елегантност с комфорт в сърцето на Варна.",
      "en": "A modern sanctuary combining elegance with comfort in the heart of Varna.",
      "ru": "Современное убежище, сочетающее элегантность и комфорт в сердце Варны.",
      "es": "Un santuario moderno que combina elegancia con comodidad en el corazón de Varna.",
      "he": "",
      "zh": ""
    },
    "category": "residential",
    "year": 2024,
    "area": 120,
    "location": "Варна, България",
    "coverImage": "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660037/projects/apartament-flavia-garden-2024/cam01.jpg",
    "images": [
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660037/projects/apartament-flavia-garden-2024/cam01.jpg",
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660140/projects/apartament-flavia-garden-2024/cam02.jpg",
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660154/projects/apartament-flavia-garden-2024/cam03.jpg",
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660156/projects/apartament-flavia-garden-2024/cam04.jpg",
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660158/projects/apartament-flavia-garden-2024/cam05.jpg",
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660159/projects/apartament-flavia-garden-2024/cam06.jpg",
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660159/projects/apartament-flavia-garden-2024/cam07.jpg",
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660160/projects/apartament-flavia-garden-2024/cam08.jpg",
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660161/projects/apartament-flavia-garden-2024/cam09.jpg",
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660038/projects/apartament-flavia-garden-2024/cam010.jpg",
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660039/projects/apartament-flavia-garden-2024/cam011.jpg",
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660041/projects/apartament-flavia-garden-2024/cam012.jpg",
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660042/projects/apartament-flavia-garden-2024/cam013.jpg",
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660043/projects/apartament-flavia-garden-2024/cam014.jpg",
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660044/projects/apartament-flavia-garden-2024/cam015.jpg",
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660045/projects/apartament-flavia-garden-2024/cam016.jpg",
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660046/projects/apartament-flavia-garden-2024/cam017.jpg",
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660047/projects/apartament-flavia-garden-2024/cam018.jpg",
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660139/projects/apartament-flavia-garden-2024/cam019.jpg",
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660142/projects/apartament-flavia-garden-2024/cam020.jpg",
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660143/projects/apartament-flavia-garden-2024/cam021.jpg",
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660147/projects/apartament-flavia-garden-2024/cam022.jpg",
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660148/projects/apartament-flavia-garden-2024/cam023.jpg",
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660149/projects/apartament-flavia-garden-2024/cam024_1.jpg",
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660150/projects/apartament-flavia-garden-2024/cam025_1.jpg",
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660151/projects/apartament-flavia-garden-2024/cam026_1.jpg",
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660153/projects/apartament-flavia-garden-2024/cam028_1.jpg",
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660153/projects/apartament-flavia-garden-2024/cam029_1.jpg",
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660155/projects/apartament-flavia-garden-2024/cam030_1.jpg"
    ],
    "published": true,
    "featured": false,
    "order": 999,
    "slug": "apartament-flavia-garden-2024",
    "originalKey": "Apartament Flavia Garden 2024"
  },
  "Work Del Mar 2022": {
    "name": {
      "bg": "Офис Дел Мар",
      "en": "Del Mar Office",
      "ru": "Офис Дель Мар",
      "es": "Oficina Del Mar",
      "he": "",
      "zh": ""
    },
    "subtitle": {
      "bg": "Модерно Работно Пространство",
      "en": "Modern Workspace",
      "ru": "Современное Рабочее Пространство",
      "es": "Espacio de Trabajo Moderno",
      "he": "",
      "zh": ""
    },
    "description": {
      "bg": "Модерен дизайн на работно пространство, насърчаващ продуктивността и благосъстоянието.",
      "en": "Modern workspace design promoting productivity and well-being.",
      "ru": "Современный дизайн рабочего пространства, способствующий продуктивности и благополучию.",
      "es": "Diseño de espacio de trabajo moderno que promueve la productividad y el bienestar.",
      "he": "",
      "zh": ""
    },
    "category": "office",
    "year": 2022,
    "area": 200,
    "location": "Варна, България",
    "coverImage": "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660299/projects/work-del-mar-2022/1%20%281%29.jpg",
    "images": [
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660299/projects/work-del-mar-2022/1%20%281%29.jpg",
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660306/projects/work-del-mar-2022/1%20%282%29.jpg",
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660308/projects/work-del-mar-2022/1%20%283%29.jpg",
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660308/projects/work-del-mar-2022/1%20%284%29.jpg",
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660310/projects/work-del-mar-2022/1%20%285%29.jpg",
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660311/projects/work-del-mar-2022/1%20%286%29.jpg",
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660313/projects/work-del-mar-2022/1%20%287%29.jpg",
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660314/projects/work-del-mar-2022/1%20%288%29.jpg",
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660315/projects/work-del-mar-2022/1%20%289%29.jpg",
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660300/projects/work-del-mar-2022/1%20%2810%29.jpg",
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660301/projects/work-del-mar-2022/1%20%2811%29.jpg",
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660303/projects/work-del-mar-2022/1%20%2812%29.jpg",
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660304/projects/work-del-mar-2022/1%20%2813%29.jpg"
    ],
    "published": true,
    "featured": false,
    "order": 999,
    "slug": "work-del-mar-2022",
    "originalKey": "Work Del Mar 2022"
  },
  "Apartament K55_2021": {
    "name": {
      "bg": "Апартамент K55",
      "en": "Apartment K55",
      "ru": "Апартамент K55",
      "es": "Apartamento K55",
      "he": "",
      "zh": ""
    },
    "subtitle": {
      "bg": "Минималистичен Дизайн",
      "en": "Minimalist Design",
      "ru": "Минималистичный Дизайн",
      "es": "Diseño Minimalista",
      "he": "",
      "zh": ""
    },
    "description": {
      "bg": "Съвременно жилищно пространство с минималистична естетика и максимална функционалност.",
      "en": "Contemporary living space with minimalist aesthetics and maximum functionality.",
      "ru": "Современное жилое пространство с минималистичной эстетикой и максимальной функциональностью.",
      "es": "Espacio de vida contemporáneo con estética minimalista y máxima funcionalidad.",
      "he": "",
      "zh": ""
    },
    "category": "residential",
    "year": 2021,
    "area": 95,
    "location": "Варна, България",
    "coverImage": "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660185/projects/apartament-k55-2021/Vladi%20%284%29.jpg",
    "images": [
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660178/projects/apartament-k55-2021/Vladi%20%281%29.jpg",
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660181/projects/apartament-k55-2021/Vladi%20%282%29.jpg",
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660183/projects/apartament-k55-2021/Vladi%20%283%29.jpg",
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660185/projects/apartament-k55-2021/Vladi%20%284%29.jpg",
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660187/projects/apartament-k55-2021/Vladi%20%285%29.jpg",
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660188/projects/apartament-k55-2021/Vladi%20%286%29.jpg",
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660190/projects/apartament-k55-2021/Vladi%20%287%29.jpg",
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660192/projects/apartament-k55-2021/Vladi%20%288%29.jpg",
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660194/projects/apartament-k55-2021/Vladi%20%289%29.jpg",
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660179/projects/apartament-k55-2021/Vladi%20%2810%29.jpg"
    ],
    "published": true,
    "featured": false,
    "order": 999,
    "slug": "apartament-k55-2021",
    "originalKey": "Apartament K55_2021"
  },
  "Elite Clinic 2021": {
    "name": {
      "bg": "Елит Клиник",
      "en": "Elite Clinic",
      "ru": "Элит Клиник",
      "es": "Clínica Elite",
      "he": "",
      "zh": ""
    },
    "subtitle": {
      "bg": "Медицинско Съоръжение",
      "en": "Medical Facility",
      "ru": "Медицинское Учреждение",
      "es": "Instalación Médica",
      "he": "",
      "zh": ""
    },
    "description": {
      "bg": "Модерно медицинско съоръжение, проектирано за комфорт на пациентите и клинична ефективност.",
      "en": "A state-of-the-art medical facility designed for patient comfort and clinical efficiency.",
      "ru": "Современное медицинское учреждение, спроектированное для комфорта пациентов и клинической эффективности.",
      "es": "Una instalación médica de última generación diseñada para la comodidad del paciente y la eficiencia clínica.",
      "he": "",
      "zh": ""
    },
    "category": "medical",
    "year": 2021,
    "area": 250,
    "location": "Варна, България",
    "coverImage": "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660177/projects/elite-clinic-2021/Cam09.jpg",
    "images": [
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660162/projects/elite-clinic-2021/Cam01.jpg",
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660171/projects/elite-clinic-2021/Cam02.jpg",
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660171/projects/elite-clinic-2021/Cam03.jpg",
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660172/projects/elite-clinic-2021/Cam04.jpg",
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660173/projects/elite-clinic-2021/Cam05.jpg",
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660174/projects/elite-clinic-2021/Cam06.jpg",
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660175/projects/elite-clinic-2021/Cam07.jpg",
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660176/projects/elite-clinic-2021/Cam08.jpg",
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660177/projects/elite-clinic-2021/Cam09.jpg",
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660163/projects/elite-clinic-2021/Cam010.jpg",
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660164/projects/elite-clinic-2021/Cam011.jpg",
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660165/projects/elite-clinic-2021/Cam012.jpg",
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660166/projects/elite-clinic-2021/Cam013.jpg",
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660167/projects/elite-clinic-2021/Cam014.jpg",
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660168/projects/elite-clinic-2021/Cam015.jpg",
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660169/projects/elite-clinic-2021/Cam016.jpg",
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660170/projects/elite-clinic-2021/Cam017.jpg"
    ],
    "published": true,
    "featured": false,
    "order": 999,
    "slug": "elite-clinic-2021",
    "originalKey": "Elite Clinic 2021"
  },
  "Apartament Траката, Варна_2021": {
    "name": {
      "bg": "Резиденция Траката",
      "en": "Trakata Residence",
      "ru": "Резиденция Траката",
      "es": "Residencia Trakata",
      "he": "",
      "zh": ""
    },
    "subtitle": {
      "bg": "Модерен Живот",
      "en": "Modern Living",
      "ru": "Современная Жизнь",
      "es": "Vida Moderna",
      "he": "",
      "zh": ""
    },
    "description": {
      "bg": "Модерната елегантност среща комфорта в този изискан жилищен проект.",
      "en": "Modern elegance meets comfort in this sophisticated residential project.",
      "ru": "Современная элегантность встречается с комфортом в этом изысканном жилом проекте.",
      "es": "La elegancia moderna se encuentra con la comodidad en este sofisticado proyecto residencial.",
      "he": "",
      "zh": ""
    },
    "category": "residential",
    "year": 2021,
    "area": 105,
    "location": "Варна, България",
    "coverImage": "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660261/projects/apartament-%D1%82%D1%80%D0%B0%D0%BA%D0%B0%D1%82%D0%B0-%D0%B2%D0%B0%D1%80%D0%BD%D0%B0-2021/1-1-2000x1200.jpg",
    "images": [
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660261/projects/apartament-%D1%82%D1%80%D0%B0%D0%BA%D0%B0%D1%82%D0%B0-%D0%B2%D0%B0%D1%80%D0%BD%D0%B0-2021/1-1-2000x1200.jpg",
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660271/projects/apartament-%D1%82%D1%80%D0%B0%D0%BA%D0%B0%D1%82%D0%B0-%D0%B2%D0%B0%D1%80%D0%BD%D0%B0-2021/2-1-768x545.jpg",
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660277/projects/apartament-%D1%82%D1%80%D0%B0%D0%BA%D0%B0%D1%82%D0%B0-%D0%B2%D0%B0%D1%80%D0%BD%D0%B0-2021/3-1-768x473.jpg",
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660277/projects/apartament-%D1%82%D1%80%D0%B0%D0%BA%D0%B0%D1%82%D0%B0-%D0%B2%D0%B0%D1%80%D0%BD%D0%B0-2021/4-1-768x666.jpg",
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660278/projects/apartament-%D1%82%D1%80%D0%B0%D0%BA%D0%B0%D1%82%D0%B0-%D0%B2%D0%B0%D1%80%D0%BD%D0%B0-2021/5-1-768x512.jpg",
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660279/projects/apartament-%D1%82%D1%80%D0%B0%D0%BA%D0%B0%D1%82%D0%B0-%D0%B2%D0%B0%D1%80%D0%BD%D0%B0-2021/6-1-768x581.jpg",
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660280/projects/apartament-%D1%82%D1%80%D0%B0%D0%BA%D0%B0%D1%82%D0%B0-%D0%B2%D0%B0%D1%80%D0%BD%D0%B0-2021/7-1-768x512.jpg",
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660281/projects/apartament-%D1%82%D1%80%D0%B0%D0%BA%D0%B0%D1%82%D0%B0-%D0%B2%D0%B0%D1%80%D0%BD%D0%B0-2021/8-1-768x689.jpg",
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660282/projects/apartament-%D1%82%D1%80%D0%B0%D0%BA%D0%B0%D1%82%D0%B0-%D0%B2%D0%B0%D1%80%D0%BD%D0%B0-2021/9-1-768x576.jpg",
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660262/projects/apartament-%D1%82%D1%80%D0%B0%D0%BA%D0%B0%D1%82%D0%B0-%D0%B2%D0%B0%D1%80%D0%BD%D0%B0-2021/10-1-768x512.jpg",
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660263/projects/apartament-%D1%82%D1%80%D0%B0%D0%BA%D0%B0%D1%82%D0%B0-%D0%B2%D0%B0%D1%80%D0%BD%D0%B0-2021/11-1-768x576.jpg",
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660264/projects/apartament-%D1%82%D1%80%D0%B0%D0%BA%D0%B0%D1%82%D0%B0-%D0%B2%D0%B0%D1%80%D0%BD%D0%B0-2021/12-1-768x512.jpg",
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660264/projects/apartament-%D1%82%D1%80%D0%B0%D0%BA%D0%B0%D1%82%D0%B0-%D0%B2%D0%B0%D1%80%D0%BD%D0%B0-2021/13-768x1132.jpg",
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660266/projects/apartament-%D1%82%D1%80%D0%B0%D0%BA%D0%B0%D1%82%D0%B0-%D0%B2%D0%B0%D1%80%D0%BD%D0%B0-2021/14-768x1024.jpg",
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660267/projects/apartament-%D1%82%D1%80%D0%B0%D0%BA%D0%B0%D1%82%D0%B0-%D0%B2%D0%B0%D1%80%D0%BD%D0%B0-2021/15-1-768x512.jpg",
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660267/projects/apartament-%D1%82%D1%80%D0%B0%D0%BA%D0%B0%D1%82%D0%B0-%D0%B2%D0%B0%D1%80%D0%BD%D0%B0-2021/16-768x1024.jpg",
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660268/projects/apartament-%D1%82%D1%80%D0%B0%D0%BA%D0%B0%D1%82%D0%B0-%D0%B2%D0%B0%D1%80%D0%BD%D0%B0-2021/17-768x1024.jpg",
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660269/projects/apartament-%D1%82%D1%80%D0%B0%D0%BA%D0%B0%D1%82%D0%B0-%D0%B2%D0%B0%D1%80%D0%BD%D0%B0-2021/18-768x1024.jpg",
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660270/projects/apartament-%D1%82%D1%80%D0%B0%D0%BA%D0%B0%D1%82%D0%B0-%D0%B2%D0%B0%D1%80%D0%BD%D0%B0-2021/19-768x1024.jpg",
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660272/projects/apartament-%D1%82%D1%80%D0%B0%D0%BA%D0%B0%D1%82%D0%B0-%D0%B2%D0%B0%D1%80%D0%BD%D0%B0-2021/20-768x1024.jpg",
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660272/projects/apartament-%D1%82%D1%80%D0%B0%D0%BA%D0%B0%D1%82%D0%B0-%D0%B2%D0%B0%D1%80%D0%BD%D0%B0-2021/21-768x1024.jpg",
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660273/projects/apartament-%D1%82%D1%80%D0%B0%D0%BA%D0%B0%D1%82%D0%B0-%D0%B2%D0%B0%D1%80%D0%BD%D0%B0-2021/22-768x1024.jpg",
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660274/projects/apartament-%D1%82%D1%80%D0%B0%D0%BA%D0%B0%D1%82%D0%B0-%D0%B2%D0%B0%D1%80%D0%BD%D0%B0-2021/23-768x1024.jpg",
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660275/projects/apartament-%D1%82%D1%80%D0%B0%D0%BA%D0%B0%D1%82%D0%B0-%D0%B2%D0%B0%D1%80%D0%BD%D0%B0-2021/24-768x1024.jpg",
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660276/projects/apartament-%D1%82%D1%80%D0%B0%D0%BA%D0%B0%D1%82%D0%B0-%D0%B2%D0%B0%D1%80%D0%BD%D0%B0-2021/25-768x1024.jpg"
    ],
    "published": true,
    "featured": false,
    "order": 999,
    "slug": "apartament-траката-варна-2021",
    "originalKey": "Apartament Траката, Варна_2021"
  },
  "Balev Corporation 2020": {
    "name": {
      "bg": "Балев Корпорация",
      "en": "Balev Corporation",
      "ru": "Балев Корпорация",
      "es": "Corporación Balev",
      "he": "",
      "zh": ""
    },
    "subtitle": {
      "bg": "Корпоративен Офис",
      "en": "Corporate Office",
      "ru": "Корпоративный Офис",
      "es": "Oficina Corporativa",
      "he": "",
      "zh": ""
    },
    "description": {
      "bg": "Динамична корпоративна централа, отразяваща иновации и професионализъм.",
      "en": "A dynamic corporate headquarters reflecting innovation and professionalism.",
      "ru": "Динамичная корпоративная штаб-квартира, отражающая инновации и профессионализм.",
      "es": "Una sede corporativa dinámica que refleja innovación y profesionalismo.",
      "he": "",
      "zh": ""
    },
    "category": "office",
    "year": 2020,
    "area": 450,
    "location": "Варна, България",
    "coverImage": "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660195/projects/balev-corporation-2020/Balev%20%281%29.jpg",
    "images": [
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660195/projects/balev-corporation-2020/Balev%20%281%29.jpg",
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660196/projects/balev-corporation-2020/Balev%20%282%29.jpg",
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660197/projects/balev-corporation-2020/Balev%20%283%29.jpg",
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660198/projects/balev-corporation-2020/Balev%20%284%29.jpg",
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660199/projects/balev-corporation-2020/Balev%20%285%29.jpg",
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660201/projects/balev-corporation-2020/Balev%20%286%29.jpg"
    ],
    "published": true,
    "featured": false,
    "order": 999,
    "slug": "balev-corporation-2020",
    "originalKey": "Balev Corporation 2020"
  },
  "Gichev sped 2019": {
    "name": {
      "bg": "Резиденция Гичев",
      "en": "Gichev Residence",
      "ru": "Резиденция Гичев",
      "es": "Residencia Gichev",
      "he": "",
      "zh": ""
    },
    "subtitle": {
      "bg": "Съвременен Дизайн",
      "en": "Contemporary Design",
      "ru": "Современный Дизайн",
      "es": "Diseño Contemporáneo",
      "he": "",
      "zh": ""
    },
    "description": {
      "bg": "Изискан семеен дом, демонстриращ съвременни дизайнерски принципи.",
      "en": "A refined family home showcasing contemporary design principles.",
      "ru": "Изысканный семейный дом, демонстрирующий современные принципы дизайна.",
      "es": "Un hogar familiar refinado que muestra principios de diseño contemporáneo.",
      "he": "",
      "zh": ""
    },
    "category": "residential",
    "year": 2019,
    "area": 130,
    "location": "Варна, България",
    "coverImage": "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660283/projects/gichev-sped-2019/GichevSped1%20%281%29.jpg",
    "images": [
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660283/projects/gichev-sped-2019/GichevSped1%20%281%29.jpg",
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660291/projects/gichev-sped-2019/GichevSped1%20%282%29.jpg",
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660292/projects/gichev-sped-2019/GichevSped1%20%283%29.jpg",
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660293/projects/gichev-sped-2019/GichevSped1%20%284%29.jpg",
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660294/projects/gichev-sped-2019/GichevSped1%20%285%29.jpg",
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660295/projects/gichev-sped-2019/GichevSped1%20%286%29.jpg",
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660296/projects/gichev-sped-2019/GichevSped1%20%287%29.jpg",
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660297/projects/gichev-sped-2019/GichevSped1%20%288%29.jpg",
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660297/projects/gichev-sped-2019/GichevSped1%20%289%29.jpg",
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660284/projects/gichev-sped-2019/GichevSped1%20%2810%29.jpg",
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660285/projects/gichev-sped-2019/GichevSped1%20%2811%29.jpg",
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660287/projects/gichev-sped-2019/GichevSped1%20%2812%29.jpg",
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660288/projects/gichev-sped-2019/GichevSped1%20%2813%29.jpg"
    ],
    "published": true,
    "featured": false,
    "order": 999,
    "slug": "gichev-sped-2019",
    "originalKey": "Gichev sped 2019"
  },
  "Oliv vilas sv.Vlas 2019": {
    "name": {
      "bg": "Олив Вили",
      "en": "Oliv Villas",
      "ru": "Олив Виллы",
      "es": "Villas Oliv",
      "he": "",
      "zh": ""
    },
    "subtitle": {
      "bg": "Луксозни Вили",
      "en": "Luxury Villas",
      "ru": "Роскошные Виллы",
      "es": "Villas de Lujo",
      "he": "",
      "zh": ""
    },
    "description": {
      "bg": "Луксозни ваканционни вили, проектирани за пълна релаксация и комфорт.",
      "en": "Luxury vacation villas designed for ultimate relaxation and comfort.",
      "ru": "Роскошные виллы для отдыха, созданные для полного расслабления и комфорта.",
      "es": "Villas vacacionales de lujo diseñadas para la máxima relajación y comodidad.",
      "he": "",
      "zh": ""
    },
    "category": "hospitality",
    "year": 2019,
    "area": 800,
    "location": "Варна, България",
    "coverImage": "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660232/projects/oliv-vilas-sv.vlas-2019/7O.V..jpg",
    "images": [
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660225/projects/oliv-vilas-sv.vlas-2019/1O.V..jpg",
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660226/projects/oliv-vilas-sv.vlas-2019/2O.V..jpg",
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660228/projects/oliv-vilas-sv.vlas-2019/3O.V..jpg",
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660230/projects/oliv-vilas-sv.vlas-2019/4O.V..jpg",
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660231/projects/oliv-vilas-sv.vlas-2019/5O.V..jpg",
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660232/projects/oliv-vilas-sv.vlas-2019/7O.V..jpg",
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660234/projects/oliv-vilas-sv.vlas-2019/8O.V..jpg",
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660235/projects/oliv-vilas-sv.vlas-2019/9O.V..jpg",
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660221/projects/oliv-vilas-sv.vlas-2019/10O.V..jpg",
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660222/projects/oliv-vilas-sv.vlas-2019/11O.V..jpg",
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660224/projects/oliv-vilas-sv.vlas-2019/12O.V..jpg"
    ],
    "published": true,
    "featured": false,
    "order": 999,
    "slug": "oliv-vilas-sv.vlas-2019",
    "originalKey": "Oliv vilas sv.Vlas 2019"
  },
  "Apartament Симфония - Бриз, Варна_ 2019": {
    "name": {
      "bg": "Симфония Бриз",
      "en": "Symphony Breeze",
      "ru": "Симфония Бриз",
      "es": "Sinfonía Brisa",
      "he": "",
      "zh": ""
    },
    "subtitle": {
      "bg": "Крайбрежен Лукс",
      "en": "Coastal Luxury",
      "ru": "Прибрежная Роскошь",
      "es": "Lujo Costero",
      "he": "",
      "zh": ""
    },
    "description": {
      "bg": "Крайбрежната елегантност среща градската изтънченост в този морски апартамент.",
      "en": "Coastal elegance meets urban sophistication in this seaside apartment.",
      "ru": "Прибрежная элегантность встречается с городской изысканностью в этой приморской квартире.",
      "es": "La elegancia costera se encuentra con la sofisticación urbana en este apartamento junto al mar.",
      "he": "",
      "zh": ""
    },
    "category": "residential",
    "year": 2019,
    "area": 110,
    "location": "Варна, България",
    "coverImage": "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660201/projects/apartament-%D1%81%D0%B8%D0%BC%D1%84%D0%BE%D0%BD%D0%B8%D1%8F-%D0%B1%D1%80%D0%B8%D0%B7-%D0%B2%D0%B0%D1%80%D0%BD%D0%B0-2019/Alex%20%281%29.jpg",
    "images": [
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660201/projects/apartament-%D1%81%D0%B8%D0%BC%D1%84%D0%BE%D0%BD%D0%B8%D1%8F-%D0%B1%D1%80%D0%B8%D0%B7-%D0%B2%D0%B0%D1%80%D0%BD%D0%B0-2019/Alex%20%281%29.jpg",
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660210/projects/apartament-%D1%81%D0%B8%D0%BC%D1%84%D0%BE%D0%BD%D0%B8%D1%8F-%D0%B1%D1%80%D0%B8%D0%B7-%D0%B2%D0%B0%D1%80%D0%BD%D0%B0-2019/Alex%20%282%29.jpg",
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660211/projects/apartament-%D1%81%D0%B8%D0%BC%D1%84%D0%BE%D0%BD%D0%B8%D1%8F-%D0%B1%D1%80%D0%B8%D0%B7-%D0%B2%D0%B0%D1%80%D0%BD%D0%B0-2019/Alex%20%283%29.jpg",
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660212/projects/apartament-%D1%81%D0%B8%D0%BC%D1%84%D0%BE%D0%BD%D0%B8%D1%8F-%D0%B1%D1%80%D0%B8%D0%B7-%D0%B2%D0%B0%D1%80%D0%BD%D0%B0-2019/Alex%20%284%29.jpg",
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660213/projects/apartament-%D1%81%D0%B8%D0%BC%D1%84%D0%BE%D0%BD%D0%B8%D1%8F-%D0%B1%D1%80%D0%B8%D0%B7-%D0%B2%D0%B0%D1%80%D0%BD%D0%B0-2019/Alex%20%285%29.jpg",
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660214/projects/apartament-%D1%81%D0%B8%D0%BC%D1%84%D0%BE%D0%BD%D0%B8%D1%8F-%D0%B1%D1%80%D0%B8%D0%B7-%D0%B2%D0%B0%D1%80%D0%BD%D0%B0-2019/Alex%20%286%29.jpg",
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660214/projects/apartament-%D1%81%D0%B8%D0%BC%D1%84%D0%BE%D0%BD%D0%B8%D1%8F-%D0%B1%D1%80%D0%B8%D0%B7-%D0%B2%D0%B0%D1%80%D0%BD%D0%B0-2019/Alex%20%287%29.jpg",
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660215/projects/apartament-%D1%81%D0%B8%D0%BC%D1%84%D0%BE%D0%BD%D0%B8%D1%8F-%D0%B1%D1%80%D0%B8%D0%B7-%D0%B2%D0%B0%D1%80%D0%BD%D0%B0-2019/Alex%20%288%29.jpg",
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660216/projects/apartament-%D1%81%D0%B8%D0%BC%D1%84%D0%BE%D0%BD%D0%B8%D1%8F-%D0%B1%D1%80%D0%B8%D0%B7-%D0%B2%D0%B0%D1%80%D0%BD%D0%B0-2019/Alex%20%289%29.jpg",
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660202/projects/apartament-%D1%81%D0%B8%D0%BC%D1%84%D0%BE%D0%BD%D0%B8%D1%8F-%D0%B1%D1%80%D0%B8%D0%B7-%D0%B2%D0%B0%D1%80%D0%BD%D0%B0-2019/Alex%20%2810%29.jpg",
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660203/projects/apartament-%D1%81%D0%B8%D0%BC%D1%84%D0%BE%D0%BD%D0%B8%D1%8F-%D0%B1%D1%80%D0%B8%D0%B7-%D0%B2%D0%B0%D1%80%D0%BD%D0%B0-2019/Alex%20%2811%29.jpg",
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660204/projects/apartament-%D1%81%D0%B8%D0%BC%D1%84%D0%BE%D0%BD%D0%B8%D1%8F-%D0%B1%D1%80%D0%B8%D0%B7-%D0%B2%D0%B0%D1%80%D0%BD%D0%B0-2019/Alex%20%2812%29.jpg",
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660205/projects/apartament-%D1%81%D0%B8%D0%BC%D1%84%D0%BE%D0%BD%D0%B8%D1%8F-%D0%B1%D1%80%D0%B8%D0%B7-%D0%B2%D0%B0%D1%80%D0%BD%D0%B0-2019/Alex%20%2813%29.jpg",
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660207/projects/apartament-%D1%81%D0%B8%D0%BC%D1%84%D0%BE%D0%BD%D0%B8%D1%8F-%D0%B1%D1%80%D0%B8%D0%B7-%D0%B2%D0%B0%D1%80%D0%BD%D0%B0-2019/Alex%20%2814%29.jpg",
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660208/projects/apartament-%D1%81%D0%B8%D0%BC%D1%84%D0%BE%D0%BD%D0%B8%D1%8F-%D0%B1%D1%80%D0%B8%D0%B7-%D0%B2%D0%B0%D1%80%D0%BD%D0%B0-2019/Alex%20%2815%29.jpg",
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660209/projects/apartament-%D1%81%D0%B8%D0%BC%D1%84%D0%BE%D0%BD%D0%B8%D1%8F-%D0%B1%D1%80%D0%B8%D0%B7-%D0%B2%D0%B0%D1%80%D0%BD%D0%B0-2019/Alex%20%2816%29.jpg",
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660217/projects/apartament-%D1%81%D0%B8%D0%BC%D1%84%D0%BE%D0%BD%D0%B8%D1%8F-%D0%B1%D1%80%D0%B8%D0%B7-%D0%B2%D0%B0%D1%80%D0%BD%D0%B0-2019/cam016.jpg",
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660218/projects/apartament-%D1%81%D0%B8%D0%BC%D1%84%D0%BE%D0%BD%D0%B8%D1%8F-%D0%B1%D1%80%D0%B8%D0%B7-%D0%B2%D0%B0%D1%80%D0%BD%D0%B0-2019/cam017.jpg",
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660219/projects/apartament-%D1%81%D0%B8%D0%BC%D1%84%D0%BE%D0%BD%D0%B8%D1%8F-%D0%B1%D1%80%D0%B8%D0%B7-%D0%B2%D0%B0%D1%80%D0%BD%D0%B0-2019/cam018.jpg",
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660220/projects/apartament-%D1%81%D0%B8%D0%BC%D1%84%D0%BE%D0%BD%D0%B8%D1%8F-%D0%B1%D1%80%D0%B8%D0%B7-%D0%B2%D0%B0%D1%80%D0%BD%D0%B0-2019/cam020.jpg"
    ],
    "published": true,
    "featured": false,
    "order": 999,
    "slug": "apartament-симфония-бриз-варна-2019",
    "originalKey": "Apartament Симфония - Бриз, Варна_ 2019"
  },
  "Playground Grand Mall Varna 2018": {
    "name": {
      "bg": "Плейграунд Гранд Мол",
      "en": "Playground Grand Mall",
      "ru": "Плейграунд Гранд Молл",
      "es": "Playground Grand Mall",
      "he": "",
      "zh": ""
    },
    "subtitle": {
      "bg": "Детски Център",
      "en": "Entertainment Center",
      "ru": "Развлекательный Центр",
      "es": "Centro de Entretenimiento",
      "he": "",
      "zh": ""
    },
    "description": {
      "bg": "Иновативен детски развлекателен център, носещ радост на семействата.",
      "en": "An innovative children's entertainment center bringing joy to families.",
      "ru": "Инновационный детский развлекательный центр, приносящий радость семьям.",
      "es": "Un innovador centro de entretenimiento infantil que trae alegría a las familias.",
      "he": "",
      "zh": ""
    },
    "category": "commercial",
    "year": 2018,
    "area": 350,
    "location": "Варна, България",
    "coverImage": "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660251/projects/playground-grand-mall-varna-2018/Playground%20%286%29.jpg",
    "images": [
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660236/projects/playground-grand-mall-varna-2018/Playground%20%281%29.jpg",
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660247/projects/playground-grand-mall-varna-2018/Playground%20%282%29.jpg",
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660248/projects/playground-grand-mall-varna-2018/Playground%20%283%29.jpg",
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660249/projects/playground-grand-mall-varna-2018/Playground%20%284%29.jpg",
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660250/projects/playground-grand-mall-varna-2018/Playground%20%285%29.jpg",
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660251/projects/playground-grand-mall-varna-2018/Playground%20%286%29.jpg",
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660252/projects/playground-grand-mall-varna-2018/Playground%20%287%29.jpg",
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660252/projects/playground-grand-mall-varna-2018/Playground%20%288%29.jpg",
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660253/projects/playground-grand-mall-varna-2018/Playground%20%289%29.jpg",
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660238/projects/playground-grand-mall-varna-2018/Playground%20%2810%29.jpg",
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660238/projects/playground-grand-mall-varna-2018/Playground%20%2811%29.jpg",
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660240/projects/playground-grand-mall-varna-2018/Playground%20%2812%29.jpg",
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660242/projects/playground-grand-mall-varna-2018/Playground%20%2813%29.jpg",
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660243/projects/playground-grand-mall-varna-2018/Playground%20%2814%29.jpg",
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660245/projects/playground-grand-mall-varna-2018/Playground%20%2815%29.jpg"
    ],
    "published": true,
    "featured": false,
    "order": 999,
    "slug": "playground-grand-mall-varna-2018",
    "originalKey": "Playground Grand Mall Varna 2018"
  },
  "Apartament Кв. Чайка, Варна_2017": {
    "name": {
      "bg": "Квартал Чайка",
      "en": "Chayka District",
      "ru": "Район Чайка",
      "es": "Distrito Chayka",
      "he": "",
      "zh": ""
    },
    "subtitle": {
      "bg": "Семеен Дом",
      "en": "Family Living",
      "ru": "Семейная Жизнь",
      "es": "Vida Familiar",
      "he": "",
      "zh": ""
    },
    "description": {
      "bg": "Топъл семеен дом, балансиращ традиционния чар с модерното удобство.",
      "en": "A warm family home balancing traditional charm with modern convenience.",
      "ru": "Теплый семейный дом, сочетающий традиционный шарм с современным удобством.",
      "es": "Un cálido hogar familiar que equilibra el encanto tradicional con la comodidad moderna.",
      "he": "",
      "zh": ""
    },
    "category": "residential",
    "year": 2017,
    "area": 85,
    "location": "Варна, България",
    "coverImage": "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660254/projects/apartament-%D0%BA%D0%B2.-%D1%87%D0%B0%D0%B9%D0%BA%D0%B0-%D0%B2%D0%B0%D1%80%D0%BD%D0%B0-2017/Dnevna01.jpg",
    "images": [
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660254/projects/apartament-%D0%BA%D0%B2.-%D1%87%D0%B0%D0%B9%D0%BA%D0%B0-%D0%B2%D0%B0%D1%80%D0%BD%D0%B0-2017/Dnevna01.jpg",
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660255/projects/apartament-%D0%BA%D0%B2.-%D1%87%D0%B0%D0%B9%D0%BA%D0%B0-%D0%B2%D0%B0%D1%80%D0%BD%D0%B0-2017/Dnevna02.jpg",
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660256/projects/apartament-%D0%BA%D0%B2.-%D1%87%D0%B0%D0%B9%D0%BA%D0%B0-%D0%B2%D0%B0%D1%80%D0%BD%D0%B0-2017/Dnevna04.jpg",
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660257/projects/apartament-%D0%BA%D0%B2.-%D1%87%D0%B0%D0%B9%D0%BA%D0%B0-%D0%B2%D0%B0%D1%80%D0%BD%D0%B0-2017/Fotev%20%282%29.jpg",
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660259/projects/apartament-%D0%BA%D0%B2.-%D1%87%D0%B0%D0%B9%D0%BA%D0%B0-%D0%B2%D0%B0%D1%80%D0%BD%D0%B0-2017/Fotev%20%283%29.jpg",
      "https://res.cloudinary.com/db1khwdaa/image/upload/v1765660260/projects/apartament-%D0%BA%D0%B2.-%D1%87%D0%B0%D0%B9%D0%BA%D0%B0-%D0%B2%D0%B0%D1%80%D0%BD%D0%B0-2017/Fotev%20%285%29.jpg"
    ],
    "published": true,
    "featured": false,
    "order": 999,
    "slug": "apartament-кв.-чайка-варна-2017",
    "originalKey": "Apartament Кв. Чайка, Варна_2017"
  }
};

// Export for use in website
if (typeof module !== 'undefined' && module.exports) {
  module.exports = projectConfig;
}
